engines:
  duplication:
    enabled: false
    config:
      languages:
        - php
  eslint:
    enabled: false
    env:
      jquery: true
  fixme:
    enabled: false
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress-VIP"
ratings:
  paths:
    - "**.js"
    - "**.php"
exclude_paths:
  - node_modules/**/*
  - languages/**
  - docs/**
  - vendor/**
  - css/**
  # - js/**
