<?php
/**
 * This file contains the Sensei_Course_Theme_Styles_Test class.
 *
 * @package sensei
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Tests for Sensei_Course_Theme_Styles class.
 *
 * @group course-theme
 */
class Sensei_Course_Theme_Styles_Test extends WP_UnitTestCase {

	/**
	 * Theme.json data injected by the current test.
	 *
	 * @var array
	 */
	private $theme_json_data = array();

	/**
	 * Clear the cached theme.json data before each test.
	 */
	public function setUp(): void {
		parent::setUp();
		wp_clean_theme_json_cache();
	}

	/**
	 * Clean up the injected theme.json data.
	 */
	public function tearDown(): void {
		$this->theme_json_data = array();
		remove_filter( 'wp_theme_json_data_theme', array( $this, 'filter_theme_json' ) );
		wp_clean_theme_json_cache();

		parent::tearDown();
	}

	/**
	 * Set the theme.json data used by the filter.
	 *
	 * @param array $data Theme.json data.
	 */
	private function set_theme_json( $data ) {
		$this->theme_json_data = $data;
		add_filter( 'wp_theme_json_data_theme', array( $this, 'filter_theme_json' ) );
	}

	/**
	 * Filter callback that merges the test theme.json data.
	 *
	 * @param WP_Theme_JSON_Data $theme_json Theme data.
	 *
	 * @return WP_Theme_JSON_Data
	 */
	public function filter_theme_json( $theme_json ) {
		return $theme_json->update_with( $this->theme_json_data );
	}

	/**
	 * Capture the CSS generated by the global styles color output.
	 *
	 * @return string
	 */
	private function capture_global_styles_colors() {
		ob_start();
		Sensei_Course_Theme_Styles::output_global_styles_colors();

		return (string) ob_get_clean();
	}

	public function testOutputGlobalStylesColors_ColorReferencesStyle_OutputsResolvedColor() {
		/* Arrange. */
		$this->set_theme_json(
			array(
				'version' => 3,
				'styles'  => array(
					'color' => array(
						'background' => '#111111',
						'text'       => array(
							'ref' => 'styles.color.background',
						),
					),
				),
			)
		);

		/* Act. */
		$output = $this->capture_global_styles_colors();

		/* Assert. */
		$this->assertStringContainsString( '--sensei-text-color-global: #111111;', $output );
	}

	public function testOutputGlobalStylesColors_ColorReferencesSetting_OutputsResolvedColor() {
		/* Arrange. */
		$this->set_theme_json(
			array(
				'version'  => 3,
				'settings' => array(
					'custom' => array(
						'brand' => '#222222',
					),
				),
				'styles'   => array(
					'color' => array(
						'text' => array(
							'ref' => 'settings.custom.brand',
						),
					),
				),
			)
		);

		/* Act. */
		$output = $this->capture_global_styles_colors();

		/* Assert. */
		$this->assertStringContainsString( '--sensei-text-color-global: #222222;', $output );
	}

	public function testOutputGlobalStylesColors_BackgroundReferencesSetting_OutputsResolvedColor() {
		/* Arrange. */
		$this->set_theme_json(
			array(
				'version'  => 3,
				'settings' => array(
					'custom' => array(
						'brand' => '#333333',
					),
				),
				'styles'   => array(
					'color' => array(
						'background' => array(
							'ref' => 'settings.custom.brand',
						),
					),
				),
			)
		);

		/* Act. */
		$output = $this->capture_global_styles_colors();

		/* Assert. */
		$this->assertStringContainsString( '--sensei-background-color-global: #333333;', $output );
	}

	public function testOutputGlobalStylesColors_LinkReferencesStyle_OutputsResolvedColor() {
		/* Arrange. */
		$this->set_theme_json(
			array(
				'version' => 3,
				'styles'  => array(
					'color'    => array(
						'background' => '#444444',
					),
					'elements' => array(
						'link' => array(
							'color' => array(
								'text' => array(
									'ref' => 'styles.color.background',
								),
							),
						),
					),
				),
			)
		);

		/* Act. */
		$output = $this->capture_global_styles_colors();

		/* Assert. */
		$this->assertStringContainsString( '--sensei-primary-color-global: #444444;', $output );
	}

	public function testOutputGlobalStylesColors_UnresolvableColorReference_OmitsColorVariable() {
		/* Arrange. */
		$this->set_theme_json(
			array(
				'version' => 3,
				'styles'  => array(
					'color' => array(
						'text' => array(
							'ref' => 'styles.color.missing',
						),
					),
				),
			)
		);

		/* Act. */
		$output = $this->capture_global_styles_colors();

		/* Assert. */
		$this->assertStringNotContainsString( '--sensei-text-color-global:', $output );
	}
}
