name: Build Hook Docs

on:
    push:
        branches:
            - master

jobs:
    hookdocs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 10
              uses: actions/setup-node@v2
              with:
                  node-version: '10.x'
            - name: npm install, and build docs
              run: |
                  npm install
                  npm run build:docs
            - name: Deploy to GH Pages
              uses: maxheld83/ghpages@v0.3.0
              env:
                  BUILD_DIR: 'hookdocs/'
                  GH_PAT: ${{ secrets.GH_PAT }}
