name: Build Hook Docs

on:
    workflow_call:

jobs:
    hookdocs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6.0.2
            - uses: actions/setup-node@v6
              with:
                  node-version-file: '.nvmrc'
            - name: npm install, and build docs
              run: |
                  npm ci
                  npm run build:docs
            - name: Deploy to GH Pages
              uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: './hookdocs'
