name: Plugin Build

on:
    - pull_request
    - workflow_call

concurrency:
    group: plugin-build-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.sha }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
    build:
        name: Plugin Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7.0.0
            - uses: actions/setup-node@v6
              with:
                  node-version-file: '.nvmrc'
            - name: Get npm cache directory
              id: npm-cache
              run: |
                  echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v5.0.5
              with:
                  path: ${{ steps.npm-cache.outputs.dir }}
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Install JS dependencies
              run: npm ci
            - name: Install PHP dependencies and generate the third-party directory
              uses: ./.github/actions/install-php
            - name: Build Plugin
              run: npm run build
            - name: Decompress plugin
              run: unzip sensei-lms.zip -d sensei-lms
            - name: Store Artifact
              uses: actions/upload-artifact@v7
              with:
                  name: sensei-lms-${{ github.event.pull_request.head.sha }}
                  path: ${{ github.workspace }}/sensei-lms/
                  retention-days: 7

    syntax-check:
        name: PHP Syntax Check
        needs: build
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [7.4, 8.2]
        steps:
            - name: Download Build Artifact
              uses: actions/download-artifact@v8
              with:
                  name: sensei-lms-${{ github.event.pull_request.head.sha }}

            - name: Setup PHP
              uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
              with:
                  php-version: ${{ matrix.php }}
                  tools: phplint
                  coverage: none

            - name: Check Syntax
              run: phplint ./sensei-lms