name: Changelogger checks

on:
  pull_request:
    branches-ignore:
      - 'release/**'
      - 'feature/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
    run:
        working-directory: sensei

jobs:
    changelogger_used:
        name: Changelogger used
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  path: sensei
            - uses: ./sensei/.github/actions/deepen-to-merge-base
              with:
                  path: sensei
            - uses: ./sensei/.github/actions/install-php
            - name: Check change files are touched for touched projects
              env:
                  BASE: ${{ github.event.pull_request.base.sha }}
                  HEAD: ${{ github.event.pull_request.head.sha }}
              run: ./scripts/check-changelogger-use.php --debug "$BASE" "$HEAD"
              working-directory: sensei
