name: E2E
on:
    pull_request:
    workflow_call:
env:
    CI: true

concurrency:
    group: e2e-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.sha }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
    test:
        name: E2E Tests
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7.0.0

            - uses: actions/setup-node@v6
              with:
                  node-version-file: '.nvmrc'

            - name: Get Node.js version
              id: node-version
              run: echo "version=$(node -v)" >> $GITHUB_OUTPUT

            - uses: actions/cache@v6.1.0
              with:
                  path: ~/.npm/
                  key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
            - uses: actions/cache@v6.1.0
              id: node-modules-cache
              with:
                  path: node_modules/
                  key: ${{ runner.os }}-${{ runner.arch }}-${{ steps.node-version.outputs.version }}-node-modules-${{ hashFiles('package-lock.json') }}

            - name: Install PHP dependencies
              uses: ./.github/actions/install-php

            - name: Install JS dependencies
              if: steps.node-modules-cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Build assets
              run: npm run build:assets

            - name: Install Playwright
              run: npx playwright install --with-deps chromium

            - name: Start wp-env
              run: npm run wp-env start

            - name: Run Playwright tests with @setup annotation
              run: CI=true npm run test:e2e:setup-only

            - name: Run Playwright tests
              run: CI=true npm run test:e2e

            - name: Archive report
              uses: actions/upload-artifact@v7
              if: failure()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
                  if-no-files-found: ignore
            - name: Slack Notification on Failure
              uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
              if: ${{ failure() && github.event_name == 'push' }}
              env:
                SLACK_CHANNEL: ${{ secrets.SLACK_SENSEI_CHANNEL }}
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                SLACK_TITLE: 'E2E Testing'
                SLACK_COLOR: 'error'
                SLACK_FOOTER: ''
