name: JS Linting and Tests

on: pull_request

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    lint:
        name: JS Linting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: ~/.npm/
                  key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
            - uses: actions/cache@v2
              with:
                  path: node_modules/
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
            - name: Install JS dependencies
              run: npm ci
            - name: Lint JS
              run: npm run lint-js

    test:
        name: JS Testing
        runs-on: ubuntu-latest
        steps:
            # clone the repository
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Install JS dependencies
              run: npm ci
            - name: Test JS
              run: npm run test-js