name: JS Linting and Tests

on: pull_request

jobs:
    lint:
        name: JS Linting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
                with:
                    node-version: '16'
                    cache: 'npm'
            - name: Install JS dependencies
              run: npm ci
            - name: Lint JS
              run: npm run lint-js

    test:
        name: JS Testing
        runs-on: ubuntu-latest
        steps:
            # clone the repository
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
                with:
                    node-version: '16'
                    cache: 'npm'
            - name: Install JS dependencies
              run: npm ci
            - name: Test JS
              run: npm run test-js
