name: JS Linting and Tests

on:
    pull_request:
    workflow_call:

jobs:
    lint:
        name: JS Linting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: ~/.npm/
                  key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
            - uses: actions/cache@v3
              with:
                  path: node_modules/
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
            - name: Install JS dependencies
              run: npm ci
            - name: Lint JS
              run: npm run lint-js
            - name: Lint TS e2e
              run: npm run lint-e2e
            - uses: ./.github/actions/slack-notification
                with:
                  slack_channel: ${{ secrets.SLACK_JANITORIAL_CHANNEL }}
                  slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
                  type: 'JS Linting'

    type-check:
        name: TypeScript Checking
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: ~/.npm/
                  key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
            - uses: actions/cache@v3
              with:
                  path: node_modules/
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
            - name: Install JS dependencies
              run: npm ci
            - name: Lint JS
              run: npm run lint-types
              
    test:
        name: JS Testing
        runs-on: ubuntu-latest
        steps:
            # clone the repository
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Install JS dependencies
              run: npm ci
            - name: Test JS
              env:
                  NODE_OPTIONS: "--max_old_space_size=4096"
              run: npm run test-js
            - name Slack Notification on Failure
              uses: ./.github/actions/slack-notification
                with:
                  slack_channel: ${{ secrets.SLACK_JANITORIAL_CHANNEL }}
                  slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
                  type: 'JS Testing'
