name: JS linting and tests

on:
  pull_request

jobs:
  lint:
    name:    JS linting
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm/
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install JS dependencies
        run: npm ci
      - name: Lint JS
        run: npm run lint-js

  test:
    name:    JS testing
    runs-on: ubuntu-16.04
    steps:
      # clone the repository
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm/
          key:  ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        with:
          path: node_modules/
          key:  ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install JS dependencies
        run: npm ci
      - name: Test JS
        run: npm run test-js