name: Pull Request Validation

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-milestone:
    name: Check Milestone
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.milestone == null
        run: |
          echo "This PR is missing a milestone."
          exit 1
      - name: Slack Notification Failure
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ${{ secrets.SLACK_JANITORIAL_CHANNEL }}
          SLACK_USERNAME: 'Sensei CI Bot'
          SLACK_COLOR: 'error'
          SLACK_ICON_EMOJI: ':jenkins-error:'
          SLACK_TITLE: 'CI Failure'
          SLACK_FOOTER: ''
