name: Test Workflow
on:
  push:
    branches:
      - add/github-ci-failure-slack-notification
jobs:
  unit-js:
    steps:
    - uses: ./.github/workflows/js.yml

    - name: Slack Notification Failure
      uses: rtCamp/action-slack-notify@v2
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: ${{ secrets.SLACK_JANITORIAL_CHANNEL }}
        SLACK_COLOR: 'error'
        SLACK_TITLE: 'CI Failure'
        SLACK_FOOTER: ''
