name: Trunk Workflow
on:
    push:
        branches:
            - trunk
jobs:
    unit-js:
        uses: ./.github/workflows/js.yml 
    unit-php:
        uses: ./.github/workflows/php.yml 
    e2e:
        uses: ./.github/workflows/e2e.yml 
    docs:
        needs: [ unit-js, unit-php, e2e ]
        uses: ./.github/workflows/build-docs.yml 
    build:
        needs: [ unit-js, unit-php, e2e ]
        uses: ./.github/workflows/build.yml
        
    wordpress-report-build:
        needs: [unit-js, unit-php, e2e]
        runs-on: ubuntu-latest
        name: WordPress Dependencies Report
        steps:
            - uses: actions/checkout@v3
            - name: Get npm cache directory
              id: npm-cache
              run: |
                  echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              with:
                  path: ${{ steps.npm-cache.outputs.dir }}
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Updates the npm version
              run: npm install -g npm@^8
            - name: Install JS dependencies
              run: npm ci
            - name: Build Combined Assets
              run: npm run build:combine-assets
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: combined-assets
                  path: ./assets/dist